# Application Name
spring.application.name=SmartPlanner

# MongoDB Connection
# Format: mongodb+srv://username:password@cluster/database
spring.data.mongodb.uri=mongodb+srv://danieleah43_db_user:AREESHA.1@cluster0.nwdzdr9.mongodb.net/smartplanner?retryWrites=true&w=majority
spring.data.mongodb.database=smartplanner

# Server Port
server.port=8080

# JWT Secret Key (production mein isko secure rakhna)
jwt.secret=SmartPlannerSecretKey2024VeryLongSecretKeyForJWTTokenGeneration
jwt.expiration=86400000

# Logging Level (development ke liye DEBUG)
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.SmartPlanner=DEBUG

# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Local Storage
file.upload-dir=uploads
file.base-url=http://localhost:8080/uploads

spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=UTC
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.adjust-dates-to-context-time-zone=false

# ==================== EMAIL CONFIGURATION ====================
# Gmail SMTP Configuration (Use App Password, not regular password)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=areeshazv@gmail.com
spring.mail.password=olxo wtgc qfpw pviq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# App Name for emails
app.name=SmartPlanner

# ==================== SCHEDULING ====================
# Enable scheduling
spring.task.scheduling.pool.size=5